---
DOWNLOAD_TAG_VER: v2.3.4
META:
  TITLE: Xstar97TheNoob
  AUTHOR: Xstar97TheNoob
  DESCRIPTION: gamer, hacker, weeb, and a noob.
  ICON_URL: favicon.png
  THEME: dark
BIO:
  ICON_URL: icon.png
  TITLE: Xstar97TheNoob
  DESCRIPTION: Gamer | Hacker | Weeb | Noob
  FOOTER: "⚔️ Get Rekt Noob! ⚔️"
BASE_SHORT_URL: https://s.xstar97thenoob.com
ENABLE_REDIRECTS: false
LINKS:
- brand: github
  icon: github
  name: GitHub
  link: "/github"
  redirects: 
- brand: web
  icon: generic-website
  name: Docs
  link: "/docs"
  redirects: 
- brand: web
  icon: generic-website
  name: APOD
  link: "/apd"
  redirects: 
- brand: discord
  icon: discord
  name: Discord Community
  link: "/discord"
  redirects: 
- brand: discord
  icon: discord
  name: Discord User
  link: "/discord/user"
  redirects: 
- brand: twitch
  icon: twitch
  name: Twitch
  link: "/tv"
  redirects: 
- brand: yt
  icon: youtube
  name: YouTube
  link: "/yt"
  redirects: 
- brand: faceb
  icon: facebook
  name: FaceBook
  link: "/fb"
  redirects: 
- brand: tiktok
  icon: tiktok
  name: TikTok
  link: "/tk"
  redirects: 
- brand: reddit
  icon: reddit
  name: Reddit
  link: "/reddit"
  redirects: 
- brand: telegram
  icon: telegram
  name: TeleGram
  link: "/telegram"
  redirects: 
- brand: twit
  icon: twitter
  name: Twitter
  link: "/tw"
  redirects: 
- brand: instagram
  icon: instagram
  name: Instagram
  link: "/insta"
  redirects: 
- brand: paypal
  icon: paypal
  name: PayPal
  link: "/paypal"
  redirects: 
- brand: patreon
  icon: patreon
  name: Patreon
  link: "/patreon"
  redirects: 
- brand: venmo
  icon: venmo
  name: Venmo
  link: "/venmo"
  redirects: 
- brand: cash-app
  icon: cash-app-dollar
  name: Cash App
  link: "/cash"
  redirects: 
- brand: onlyfans
  icon: onlyfans
  name: OnlyFans
  link: "/onlyfans"
  redirects: 
- brand: ko-fi
  icon: ko-fi
  name: Ko-Fi
  link: "/ko-fi"
  redirects: 
- brand: web
  icon: generic-website
  name: Stake US
  link: "/stakeus"
  redirects: 
